version: "3.7"

services:
  rollapp:
    container_name: rollapp
    image: "__IMAGE__"
    restart: always
    environment:
      NODE_ENV: production
      DEMO_MODE: "false"
      PORT: "8080"
      COOKIE_SECURE: "true"
      APP_VERSION: "__VERSION__"
      PGHOST: "c-c9q11j9k294u5dmlk127.rw.mdb.yandexcloud.net"
      PGPORT: "6432"
      PGDATABASE: "rollapp"
      PGUSER: "rollapp_app"
      PG_POOL_SIZE: "8"
      YC_LOCKBOX_SECRET_ID: "e6qn7uuqpp2jg3krbh4u"
      YC_LOCKBOX_SECRET_KEY: "postgresql_password"
      PUBLIC_HOST: "xn--80avakiab.xn--p1ai"
      REDIRECT_HOSTS: "rollapp.51-250-110-17.sslip.io, www.xn--80avakiab.xn--p1ai"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/lib/rollapp-caddy:/data
      - /var/lib/rollapp-caddy-config:/config
